# Dependencies
markdown:         kramdown
highlighter:      pygments

# Setup
title:            Conrad Lee
tagline:          'A data portfolio'
description:      "A data portfolio"
url:              http://hyde.getpoole.com
baseurl:          https://conradlee123.github.io/

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
plugins:          [jekyll-paginate]